### ISSUE TITLE
vector icon throwing exception

### ISSUE THREAD

**Issue by aayush0208** [robertlevonyan/material-chip-view#83]
creating and adding chip to the ChipsGroup

 for (i in selectedStates){
            val chip = Chip(this)
            chip.text = i
            chip.setBackgroundColor(Color.parseColor("#2929290D"))
            chip.chipIcon = ContextCompat.getDrawable(this, R.drawable.ic_close)
            work_location_chipgroup.addView(chip)
            chip.setOnClickListener{
                work_location_chipgroup.removeView(it)
            }
        }

When adding vector icon to the chip, app is crashing with below exception:
java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

**Comment by robertlevonyan** [comment]
You need to convert vector drawable to a bitmap drawable

**Comment by aayush0208** [comment]
isn't there a way to use vector icons?

**Comment by robertlevonyan** [comment]
Just wrap your vector drawable into a bitmap drawable
